#pragma once

#define RADIO_READ_BUTTON_PIN 21
#define RADIO_TRANSMIT_BUTTON_PIN 20

#define NFC_READ_BUTTON_PIN 21
#define NFC_WRITE_BUTTON_PIN 20

#define LED_PIN 10

#define SIGNAL_SLOTS 10

#define NFC_READ_TIMEOUT_MS 10000

